import { useState } from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import "./index.scss";

import UserNavbar from "./components/User/UserNavbar";
import User from "./components/User/User";

import HomeNavbar from "./components/Home/components/homeNavbar";
import HomePage from "./components/Home/HomePage";

function App() {
  return (
    <>
      <BrowserRouter>
        <Routes>
          {/* Route index (home) page */}
          <Route path="/" element={<HomeNavbar />}>
            <Route index element={<HomePage />} />
          </Route>

          <Route path="/user" element={<UserNavbar />}>
            <Route path={''} element={<User />}>
              <Route index element={<p className="tx-white"><br /><br /> NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR NASHRLAR </p>} />
              <Route path="about" element={<p className="tx-white"><br /><br /> MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA MEN HAQIMDA </p>} />
              <Route path="saved" element={<p className="tx-white"><br /><br /> SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR SAQLANGANLAR </p>} /> 
            </Route>
            <Route path="settings" element={<p>settings</p>}/>
          </Route>

          {/* Route singup / singin page */}
        </Routes>
      </BrowserRouter>
    </>
  );
}

export default App;
